networks:
  algafood-network:
    driver: bridge

services:
  algafood-postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: algafood
    ports:
      - "7653:5432"
    networks: 
      - algafood-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d algafood"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s  

  algafood-api:
    build: .
    image: algafood-api
    environment:
      DB_HOST: algafood-postgres
    ports:
      - "8080:8080"
    networks:
      - algafood-network
    depends_on:
      algafood-postgres:
        condition: service_healthy
        restart: true
