insert into cozinha (nome) values ('Tailandesa');
insert into cozinha (nome) values ('Brasileira');

insert into restaurante (nome, taxa_frete, cozinha_id) values ('Picanha do Márcio', 5.50, 2);
insert into restaurante (nome, taxa_frete, cozinha_id) values ('Cozinha do Tio Won', 11.27, 1);

insert into estado(nome) values ('Pernambuco'),('Paraíba'), ('Ceará'), ('Rio de Janeiro'), ('São Paulo');
insert into estado(nome) values ('Acre'), ('Amazônia'), ('Pará'), ('Bahia'), ('Alagoas'), ('Santa Catarina');
insert into estado(nome) values ('Rio Grande do Sul'), ('Rio Grande do Norte'), ('Mato Grosso'), ('Mato Grosso do Sul');
insert into estado(nome) values ('Brasília'), ('Paraná'), ('Piauí'), ('Sergipe'), ('Maranhão'), ('Góias');
insert into estado(nome) values ('Espírito Santo'), ('Tocatins'), ('Amapá'), ('Roraima'), ('Rondônia'), ('Minas Gerais');

insert into cidade (nome, estado_id) values ('Recife', 1);
insert into cidade (nome, estado_id) values ('João Pessoa', 2);
insert into cidade (nome, estado_id) values ('Fortaleza', 3);
insert into cidade (nome, estado_id) values ('Rio de Janeiro', 4);
insert into cidade (nome, estado_id) values ('São Paulo', 5);
insert into cidade (nome, estado_id) values ('Rio Branco', 6);
insert into cidade (nome, estado_id) values ('Manaus', 7);
insert into cidade (nome, estado_id) values ('Belém', 8);
insert into cidade (nome, estado_id) values ('Salvador', 9);
insert into cidade (nome, estado_id) values ('Maceió', 10);
insert into cidade (nome, estado_id) values ('Florianópolis', 11);
insert into cidade (nome, estado_id) values ('Porto Alegre', 12);
insert into cidade (nome, estado_id) values ('Natal', 13);
insert into cidade (nome, estado_id) values ('Cuiabá', 14);
insert into cidade (nome, estado_id) values ('Campo Grande', 15);
insert into cidade (nome, estado_id) values ('Brasília', 16);
insert into cidade (nome, estado_id) values ('Curitiba', 17);
insert into cidade (nome, estado_id) values ('Teresina', 18);
insert into cidade (nome, estado_id) values ('Aracaju', 19);
insert into cidade (nome, estado_id) values ('São Luís', 20);
insert into cidade (nome, estado_id) values ('Goiânia', 21);
insert into cidade (nome, estado_id) values ('Vitória', 22);
insert into cidade (nome, estado_id) values ('Palmas', 23);
insert into cidade (nome, estado_id) values ('Macapá', 24);
insert into cidade (nome, estado_id) values ('Boa Vista', 25);
insert into cidade (nome, estado_id) values ('Porto Velho', 26);
insert into cidade (nome, estado_id) values ('Belo Horizonte', 27);
insert into cidade (nome, estado_id) values ('Olinda', 1);
insert into cidade (nome, estado_id) values ('Campina Grande', 2);
insert into cidade (nome, estado_id) values ('Sobral', 3);
insert into cidade (nome, estado_id) values ('Niterói', 4);
insert into cidade (nome, estado_id) values ('Santos', 5);
insert into cidade (nome, estado_id) values ('Cruzeiro do Sul', 6);
insert into cidade (nome, estado_id) values ('Parintins', 7);
insert into cidade (nome, estado_id) values ('Marabá', 8);
insert into cidade (nome, estado_id) values ('Feira de Santana', 9);
insert into cidade (nome, estado_id) values ('Arapiraca', 10);
insert into cidade (nome, estado_id) values ('Joinville', 11);
insert into cidade (nome, estado_id) values ('Caxias do Sul', 12);
insert into cidade (nome, estado_id) values ('Mossoró', 13);
insert into cidade (nome, estado_id) values ('Rondonópolis', 14);
insert into cidade (nome, estado_id) values ('Dourados', 15);
insert into cidade (nome, estado_id) values ('Taguatinga', 16);
insert into cidade (nome, estado_id) values ('Londrina', 17);
insert into cidade (nome, estado_id) values ('Parnaíba', 18);
insert into cidade (nome, estado_id) values ('Lagarto', 19);
insert into cidade (nome, estado_id) values ('Imperatriz', 20);
insert into cidade (nome, estado_id) values ('Anápolis', 21);
insert into cidade (nome, estado_id) values ('Guarapari', 22);
insert into cidade (nome, estado_id) values ('Gurupi', 23);
insert into cidade (nome, estado_id) values ('Santana', 24);
insert into cidade (nome, estado_id) values ('Rorainópolis', 25);
insert into cidade (nome, estado_id) values ('Ji-Paraná', 26);
insert into cidade (nome, estado_id) values ('Uberlândia', 27);
insert into cidade (nome, estado_id) values ('Caruaru', 1);
insert into cidade (nome, estado_id) values ('Patos', 2);
insert into cidade (nome, estado_id) values ('Juazeiro do Norte', 3);
insert into cidade (nome, estado_id) values ('Petrópolis', 4);
insert into cidade (nome, estado_id) values ('Campinas', 5);
insert into cidade (nome, estado_id) values ('Sena Madureira', 6);
insert into cidade (nome, estado_id) values ('Itacoatiara', 7);
insert into cidade (nome, estado_id) values ('Castanhal', 8);
insert into cidade (nome, estado_id) values ('Ilhéus', 9);
insert into cidade (nome, estado_id) values ('Penedo', 10);
insert into cidade (nome, estado_id) values ('Blumenau', 11);
insert into cidade (nome, estado_id) values ('Pelotas', 12);
insert into cidade (nome, estado_id) values ('Caicó', 13);
insert into cidade (nome, estado_id) values ('Sinop', 14);
insert into cidade (nome, estado_id) values ('Três Lagoas', 15);
insert into cidade (nome, estado_id) values ('Gama', 16);
insert into cidade (nome, estado_id) values ('Maringá', 17);
insert into cidade (nome, estado_id) values ('Picos', 18);
insert into cidade (nome, estado_id) values ('Itabaiana', 19);
insert into cidade (nome, estado_id) values ('Caxias', 20);
insert into cidade (nome, estado_id) values ('Aparecida de Goiânia', 21);
insert into cidade (nome, estado_id) values ('Serra', 22);
insert into cidade (nome, estado_id) values ('Araguaína', 23);
insert into cidade (nome, estado_id) values ('Laranjal do Jari', 24);
insert into cidade (nome, estado_id) values ('Pacaraima', 25);
insert into cidade (nome, estado_id) values ('Ariquemes', 26);
insert into cidade (nome, estado_id) values ('Contagem', 27);